


import java.awt.Image;
import javax.swing.ImageIcon;


public class LandingPage extends javax.swing.JFrame {

    
    public LandingPage() {
        initComponents();
        
        // LANDING IMAGE
        ImageIcon tempImage = new ImageIcon ("C:\\Users\\Grace\\Documents\\NetBeansProjects\\Semester5_FinalProject\\src\\landings.png");
        Image scaledImage = tempImage.getImage().getScaledInstance(500, 450,Image.SCALE_SMOOTH); 
        ImageIcon finalImage = new ImageIcon(scaledImage);
        landingIcon.setIcon(finalImage);
        landingIcon.setText("");
        // LOGO
        ImageIcon templogo = new ImageIcon ("C:\\Users\\Grace\\Documents\\NetBeansProjects\\Semester5_FinalProject\\src\\logos.png");
        Image scaledlogo = templogo.getImage().getScaledInstance(35, 35,Image.SCALE_SMOOTH); 
        ImageIcon finallogo = new ImageIcon(scaledlogo);
        logo.setIcon(finallogo);
        logo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientB = new javax.swing.JButton();
        landingIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        doctorB = new javax.swing.JButton();
        staffB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ourDocB = new javax.swing.JButton();
        aboutUsB = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 514));

        patientB.setBackground(new java.awt.Color(204, 102, 0));
        patientB.setFont(new java.awt.Font("DengXian", 1, 18)); // NOI18N
        patientB.setForeground(new java.awt.Color(255, 255, 255));
        patientB.setText("Let's Go !");
        patientB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBActionPerformed(evt);
            }
        });

        landingIcon.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        doctorB.setFont(new java.awt.Font("DengXian", 1, 14)); // NOI18N
        doctorB.setForeground(new java.awt.Color(255, 204, 51));
        doctorB.setText("Doctor Login");
        doctorB.setBorderPainted(false);
        doctorB.setContentAreaFilled(false);
        doctorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorBActionPerformed(evt);
            }
        });

        staffB.setFont(new java.awt.Font("DengXian", 1, 14)); // NOI18N
        staffB.setForeground(new java.awt.Color(255, 204, 51));
        staffB.setText("Staff Login");
        staffB.setBorderPainted(false);
        staffB.setContentAreaFilled(false);
        staffB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setText("Hospital Tap");

        ourDocB.setFont(new java.awt.Font("DengXian", 1, 14)); // NOI18N
        ourDocB.setForeground(new java.awt.Color(255, 204, 51));
        ourDocB.setText("Our Doctors");
        ourDocB.setBorderPainted(false);
        ourDocB.setContentAreaFilled(false);
        ourDocB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourDocBActionPerformed(evt);
            }
        });

        aboutUsB.setFont(new java.awt.Font("DengXian", 1, 14)); // NOI18N
        aboutUsB.setForeground(new java.awt.Color(255, 204, 102));
        aboutUsB.setText("Home");
        aboutUsB.setBorderPainted(false);
        aboutUsB.setContentAreaFilled(false);
        aboutUsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsBActionPerformed(evt);
            }
        });

        logo.setText("jLabel8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(aboutUsB)
                .addGap(18, 18, 18)
                .addComponent(ourDocB)
                .addGap(18, 18, 18)
                .addComponent(doctorB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staffB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutUsB)
                    .addComponent(ourDocB)
                    .addComponent(doctorB)
                    .addComponent(staffB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("STZhongsong", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Hospital Service <3");

        jLabel4.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        jLabel4.setText("Welcome to Hospital Tap Indonesia, where we are dedicated to");

        jLabel3.setFont(new java.awt.Font("STZhongsong", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("All-in-One renown");

        jLabel5.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        jLabel5.setText("providing exceptional healthcare services to our patients.");

        jLabel6.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        jLabel6.setText("As a leading provider of medical care, we are committed to ");

        jLabel7.setFont(new java.awt.Font("STZhongsong", 0, 12)); // NOI18N
        jLabel7.setText("delivering high-quality, patient-centered care to those in need.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientB, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(landingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(patientB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(landingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBActionPerformed
        SignUp signup = new SignUp();
        signup.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_patientBActionPerformed

    private void doctorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorBActionPerformed
       DoctorLogin doctor = new DoctorLogin();
       doctor.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_doctorBActionPerformed

    private void staffBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffBActionPerformed
       StaffLogin staff = new StaffLogin();
       staff.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_staffBActionPerformed

    private void ourDocBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourDocBActionPerformed
        OurDocs docpage = new OurDocs();
        docpage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ourDocBActionPerformed

    private void aboutUsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutUsB;
    private javax.swing.JButton doctorB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel landingIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JButton ourDocB;
    private javax.swing.JButton patientB;
    private javax.swing.JButton staffB;
    // End of variables declaration//GEN-END:variables
}
